---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-helm-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: source-prometheus-stack
      valuesFiles:
        - https://github.com/cloudnative-pg/cloudnative-pg/blob/main/docs/src/samples/monitoring/kube-stack-config.yaml
  interval: 10s
  targetNamespace: monitoring
