---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux-helm-prometheus-stack
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: source-prometheus-stack
      values:
        enabled: true
        kubeControllerManager:
          enabled: false
        nodeExporter:
          enabled: false
        defaultRules:
          create: true
          rules:
            alertmanager: false
            etcd: false
            configReloaders: false
            general: false
            k8s: true
            kubeApiserver: false
            kubeApiserverAvailability: false
            kubeApiserverSlos: false
            kubelet: true
            kubeProxy: false
            kubePrometheusGeneral: false
            kubePrometheusNodeRecording: false
            kubernetesApps: false
            kubernetesResources: false
            kubernetesStorage: false
            kubernetesSystem: false
            kubeScheduler: false
            kubeStateMetrics: false
            network: false
            node: true
            nodeExporterAlerting: false
            nodeExporterRecording: true
            prometheus: false
            prometheusOperator: false

        #nodeSelector:
          #workload: monitor
        prometheus:
          prometheusSpec:
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
          #nodeSelector:
          #workload: monitor
        grafana:
          enabled: true
          # -- the grafana admin password
          adminPassword: prom-operator
          defaultDashboardsEnabled: false
          sidecar:
            dashboards:
              enabled: true
          #nodeSelector:
            #workload: monitor
        alertmanager:
          enabled: true
          #alerManagerSpec:
            #nodeSelector:
              #workload: monitorl
  interval: 10s
  targetNamespace: monitoring
