---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: source-bg-demo
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/anilson87/cnpg-web-helm1
