---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: source-prometheus-stack
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/prometheus-community/helm-charts/tree/main/charts
